_fw_name: CommonAdapter
_fw_q_type: SLURM
rocket_launch: rlaunch -w /home/kit/iam-cms/lr1762/.fireworks/fworker_uc2.yaml -l /home/kit/iam-cms/lr1762/.fireworks/launchpad_kit.yaml singleshot
#ntasks: 1
#cpus_per_task: 1
#ntasks_per_node: 1
#walltime: '00:02:00'
#queue: single
#account: null
job_name: null
pre_rocket: null
post_rocket: null

#You can also supply your own template by uncommenting and changing the following line:
_fw_template_file: '/home/kit/iam-cms/lr1762/tools/cluster/submit_postproc_uc2.txt'
