_fw_name: CommonAdapter
_fw_q_type: SLURM
rocket_launch: rlaunch -w /home/kit/iam-cms/lr1762/.fireworks/fworker_uc2.yaml -l /home/kit/iam-cms/lr1762/.fireworks/launchpad_kit_cluster.yaml singleshot
nodes: 1
ntasks: 1
walltime: '00:02:00'
queue: single
account: null
job_name: null
pre_rocket: export KMP_AFFINITY=compact,1,0 ; module load compiler/intel/19.1 ; module load mpi/openmpi/4.0
post_rocket: null

#logdir: /home/kit/iam-cms/lr1762/fw_logs

# You can override commands by uncommenting and changing the following lines:
# _q_commands_override:
#    submit_cmd: my_qsubmit
#    status_cmd: my_qstatus

#You can also supply your own template by uncommenting and changing the following line:
#_fw_template_file: '/home/kit/iam-cms/lr1762/tools/cluster/submit_sim_uc2.txt'
